"""
Post benchmark results as a GitHub PR comment.

Called by the benchmark.yml workflow after ci_benchmark.sh completes.
Reads the JSON result from BENCHMARK_RESULT_FILE (default: /tmp/benchmark_result.json).

Required env vars:
  GITHUB_TOKEN           — provided automatically by GitHub Actions
  CI_REPO                — e.g. "toddwillis/ngw-core"
  CI_PR_NUMBER           — pull request number (integer)
  BENCHMARK_RESULT_FILE  — path to the JSON result file
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request
import urllib.error
from pathlib import Path


_GITHUB_API = "https://api.github.com"


def _github_request(method: str, path: str, body: dict | None = None) -> dict:
    token = os.environ["GITHUB_TOKEN"]
    url   = f"{_GITHUB_API}{path}"
    data  = json.dumps(body).encode() if body else None
    req   = urllib.request.Request(
        url,
        data    = data,
        method  = method,
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept":        "application/vnd.github+json",
            "Content-Type":  "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def _format_comment(result: dict) -> str:
    exit_code    = result.get("exit_code", 0)
    status       = result.get("status", "unknown")
    score        = result.get("overall_score")
    pat_acc      = result.get("pattern_accuracy")
    bp_score     = result.get("avg_blueprint_score")
    conf_err     = result.get("confidence_error")
    total_cases  = result.get("total_cases")
    passed_cases = result.get("passed_cases")
    regressions  = result.get("regressions", [])
    improvements = result.get("improvements", [])
    insights     = result.get("insights", [])
    run_id       = result.get("run_id", "—")

    if exit_code == 0:
        header = "## ✅ Benchmark Passed\n\nSafe to merge ✓"
    else:
        header = "## ❌ Benchmark Regression Detected\n\n🚫 **Deployment Blocked** — fix regressions before merging."

    # Score table
    score_str  = f"{score:.3f}"  if score  is not None else "—"
    pat_str    = f"{pat_acc:.1%}" if pat_acc is not None else "—"
    bp_str     = f"{bp_score:.3f}" if bp_score is not None else "—"
    conf_str   = f"{conf_err:+.3f}" if conf_err is not None else "—"
    cases_str  = f"{passed_cases}/{total_cases}" if total_cases else "—"

    table = (
        "\n\n| Metric | Value |\n"
        "|--------|-------|\n"
        f"| Overall Score | **{score_str}** |\n"
        f"| Pattern Accuracy | {pat_str} |\n"
        f"| Blueprint Score | {bp_str} |\n"
        f"| Confidence Error | {conf_str} |\n"
        f"| Cases Passed | {cases_str} |\n"
        f"| Run ID | `{run_id}` |"
    )

    body = header + table

    # Regressions
    if regressions:
        body += f"\n\n### ⚠️ Regressions ({len(regressions)})\n"
        for reg in regressions[:8]:
            rtype  = reg.get("type", "?")
            pid    = reg.get("pattern_id", "overall")
            delta  = reg.get("delta", 0) * 100
            body  += f"- **{rtype}** `{pid}` Δ{delta:+.1f}%\n"

    # Improvements
    if improvements:
        body += f"\n\n### 📈 Improvements ({len(improvements)})\n"
        for imp in improvements[:5]:
            itype = imp.get("type", "?")
            pid   = imp.get("pattern_id", "overall")
            delta = imp.get("delta", 0) * 100
            body += f"- **{itype}** `{pid}` Δ{delta:+.1f}%\n"

    # Insights
    if insights:
        body += "\n\n### 💡 Insights\n"
        for ins in insights[:5]:
            body += f"- {ins}\n"

    body += "\n\n---\n*🤖 Generated by [NGW Benchmark CI](/.github/workflows/benchmark.yml)*"
    return body


def _find_existing_comment(repo: str, pr_number: int) -> int | None:
    """Return ID of first existing bot comment on this PR, or None."""
    path = f"/repos/{repo}/issues/{pr_number}/comments?per_page=100"
    try:
        comments = _github_request("GET", path)
    except urllib.error.HTTPError:
        return None
    for c in comments:
        if (
            c.get("user", {}).get("type") == "Bot"
            and "NGW Benchmark CI" in (c.get("body") or "")
        ):
            return c["id"]
    return None


def main() -> None:
    result_file = os.environ.get("BENCHMARK_RESULT_FILE", "/tmp/benchmark_result.json")
    repo        = os.environ.get("CI_REPO", "")
    pr_str      = os.environ.get("CI_PR_NUMBER", "")

    if not repo or not pr_str:
        print("CI_REPO or CI_PR_NUMBER not set — skipping PR comment.", file=sys.stderr)
        sys.exit(0)

    try:
        pr_number = int(pr_str)
    except ValueError:
        print(f"Invalid CI_PR_NUMBER: {pr_str!r}", file=sys.stderr)
        sys.exit(0)

    result_path = Path(result_file)
    if not result_path.exists():
        print(f"Result file not found: {result_file}", file=sys.stderr)
        sys.exit(0)

    result  = json.loads(result_path.read_text())
    comment = _format_comment(result)

    existing_id = _find_existing_comment(repo, pr_number)
    if existing_id:
        print(f"Updating existing comment {existing_id} on PR #{pr_number}...")
        _github_request("PATCH", f"/repos/{repo}/issues/comments/{existing_id}", {"body": comment})
    else:
        print(f"Creating new comment on PR #{pr_number}...")
        _github_request("POST", f"/repos/{repo}/issues/{pr_number}/comments", {"body": comment})

    print("✓ PR comment posted.")


if __name__ == "__main__":
    main()
